name: Vespa Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest --maxfail=3 --disable-warnings --cov=vespa

  build:
    name: Build and Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Build Package
        run: poetry build

      - name: Extract Version
        id: get_version
        run: echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV

      - name: Build and zip docs
        shell: bash
        run: |
          poetry run task bdocs
          zip -r vespa_docs.zip site/
        working-directory: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Vespa ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/*.tar.gz
            dist/*.whl
            vespa_docs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
