lr: 1e-6                          # Learning rate to optimizer
momentum: 0.9                     # used if SGD choice. DEFAULT is Adam
weight_decay: 5e-6                # Weight decay to optmizer
horizontal_flip: 0.4              # probability to apply
brightness: 0.4                   # used on random_brightness_contrast. Gain +- (-0.4, 0.4)
contrast: 0.4                     # used on random_brightness_contrast. Gain +- (-0.4, 0.4)
b_c_probability: 0.3              # probability to apply brightness and contrast
hue: 20                           # used on hue_saturation_value. Gain +- (-20, 20)
sat: 30                           # used on hue_saturation_value. Gain +- (-30, 20)
val: 20                           # used on hue_saturation_value. Gain +- (-20, 20)
h_s_v_probability: 0.2            # probability to apply
translate: 0.05                   # used on shift_scale_rotate. Gain +- (-0.05, 0.05)
scale: 0.5                        # used on shift_scale_rotate. Gain +- (-0.5, 0.5)
rotate: 30                        # used on shift_scale_rotate. Gain +- (-30, 30)
t_s_r_probability: 0.3            # probability to apply translate, scale, and rotate
min_visibility: 0.6               # Minimal percentage of visibility from bounding boxes